### PR TITLE
Use injected HttpClient for loader

### LINKED ISSUE #121: OPTIONS request against service to load extension can require credentials
Stems from https://github.com/Islandora-CLAW/CLAW/issues/612#issuecomment-306817641

When the Loader Service is making an OPTIONS request against a service to load an extension, it does not provide credentials.  This causes the loader service to fail when the attempting to load a service that requires authentication for OPTIONS requests.

### PR DESCRIPTION
**Pull request by birkland**
The loader's interaction with a service with respect to OPTIONS now occurs
through the registry HttpClient, which can be configured for
authentication

Resolves #121

### CODE REVIEW

**Comment by dannylamb** [comment]
@birkland I can test this out for you in Islandora later today.

File: fcrepo-api-x-loader/src/main/java/org/fcrepo/apix/loader/impl/LoaderRoutes.java [hunk 1]
```diff
@@ -125,7 +125,7 @@ public void configure() throws Exception {
                 .setHeader(Exchange.HTTP_URI, header(HEADER_SERVICE_URI))
                 .setHeader("Accept", constant("text/turtle"))
                 .process(e -> LOG.info("Execution OPTIONS to service URI {}", e.getIn().getHeader(Exchange.HTTP_URI)))
-                .to("jetty:http://localhost")
+                .to("http://localhost?httpClient=#httpClient")
```
Comment (dannylamb) [inline fcrepo-api-x-loader/src/main/java/org/fcrepo/apix/loader/impl/LoaderRoutes.java:128]: Oh man, that's smart.  I didn't know you could throw bean refs at it using #

Comment (ajs6f) [reply fcrepo-api-x-loader/src/main/java/org/fcrepo/apix/loader/impl/LoaderRoutes.java:128]: Yeah, the param name was the thing [we weren't sure whether it was legit](https://issues.apache.org/jira/browse/CAMEL-11270), but `#` works all over.

**Comment by dannylamb** [comment]
It works. I just integrated our OCR service with Api-X using this changeset.

```bash
ubuntu@claw:/var/www/html/Crayfish/Hypercube$ curl -I -H "Authorization: Bearer islandora" http://localhost:8081/fcrepo/rest/test.tiff
HTTP/1.1 200 OK
Content-Type: image/tiff
Accept: */*
Accept-Ranges: bytes
Allow: DELETE,HEAD,GET,PUT,OPTIONS
Apix-Modality: intercept; outgoing
Authorization: Bearer islandora
breadcrumbId: ID-claw-43528-1497022083888-5-159
Content-Disposition: attachment; filename=""; creation-date="Fri, 09 Jun 2017 18:14:06 GMT"; modification-date="Fri, 09 Jun 2017 18:14:06 GMT"; size=20648
ETag: "56156efacc6fc99274a19d102f95a2ed9e31d89e"
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Last-Modified: Fri, 09 Jun 2017 18:14:06 GMT
Link: <http://www.w3.org/ns/ldp#NonRDFSource>;rel="type"
Link: <http://localhost:8081/fcrepo/rest/test.tiff/fcr:metadata>; rel="describedby"
Link: <http://localhost:8081/discovery/test.tiff>; rel="service"
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
Server: Apache-Coyote/1.1
Content-Length: 0

ubuntu@claw:/var/www/html/Crayfish/Hypercube$ curl -H "Authorization: Bearer islandora" http://localhost:8081/discovery/test.tiff
<>      a       <http://fedora.info/definitions/v4/service#ServiceDocument> ;
        <http://fedora.info/definitions/v4/service#isServiceDocumentFor>
                <http://localhost:8081/fcrepo/rest/test.tiff> ;
        <http://www.openarchives.org/ore/terms/describes>
                <#services> .

<#services>  <http://www.openarchives.org/ore/terms/aggregates>
                <#f920f7df-652a-4f27-b9ae-5ff9a33f9a02> .

<#f920f7df-652a-4f27-b9ae-5ff9a33f9a02>
        a       <http://fedora.info/definitions/v4/service#ServiceInstance> ;
        <http://fedora.info/definitions/v4/service#hasEndpoint>
                <http://localhost:8081/services/test.tiff/svc:ocr> ;
        <http://fedora.info/definitions/v4/service#isFunctionOf>
                <http://localhost:8081/fcrepo/rest/test.tiff> ;
        <http://fedora.info/definitions/v4/service#isServiceInstanceOf>
                <http://islandora.ca/CLAW#OcrService> ;
        <http://fedora.info/definitions/v4/service#serviceInstanceExposedBy>
                <http://localhost:8081/fcrepo/rest/test.tiff> .

ubuntu@claw:/var/www/html/Crayfish/Hypercube$ curl -H "Authorization: Bearer islandora" http://localhost:8081/services/test.tiff/svc:ocr
Test tiff
Test tiff
Test tiff
Test tiff
```

<image src="https://m.popkey.co/6e40d1/5OWd_f-maxage-0.gif"/>

**Comment by birkland** [comment]
@dannylamb That's fantastic!  I wish I had celebratory animated gif skills, but maybe celebratory draught skills will do.

**Comment by ajs6f** [comment]
on our way
